POST http://localhost:8000/login
Content-Type: application/json

{
	"username": "hey18",
	"password": "password"
}

###
POST http://localhost:8000/signup
Content-Type: application/json

{
	"username": "hey20",
	"password": "password",
	"email": "sirawat.i@ku.th"
}

###
POST http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxNTQ5OTU3LCJpYXQiOjE2OTAwMTM5NTcsImp0aSI6ImRlNTI1MjVhNjI0NTQ2OGZhODY3MTk0YmI1MzhmODBhIiwidXNlcl9pZCI6Mn0.AfjLJ2JtS26RDkBqm9YmscmQ3r-Riw_pYmgf5EsrrRc
Content-Type: application/json

{
	"name":"product nameah",
	"brand":"product brand",
	"region":"product region",
	"stock":1,
	"price": 100.0
}

###
# GET http://localhost:8000/products?name=product&brand=product&region=product
GET http://localhost:8000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxNTQ5OTU3LCJpYXQiOjE2OTAwMTM5NTcsImp0aSI6ImRlNTI1MjVhNjI0NTQ2OGZhODY3MTk0YmI1MzhmODBhIiwidXNlcl9pZCI6Mn0.AfjLJ2JtS26RDkBqm9YmscmQ3r-Riw_pYmgf5EsrrRc
Content-Type: application/json

###
POST http://localhost:8000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxNTQ5OTU3LCJpYXQiOjE2OTAwMTM5NTcsImp0aSI6ImRlNTI1MjVhNjI0NTQ2OGZhODY3MTk0YmI1MzhmODBhIiwidXNlcl9pZCI6Mn0.AfjLJ2JtS26RDkBqm9YmscmQ3r-Riw_pYmgf5EsrrRc
Content-Type: application/json

{
	"name": "this order is for test purpose",
	"shopping_cart": [
		{
			"product_id": 9,
			"quantity": 2
		},
		{
			"product_id": 10,
			"quantity": 3
		},
		{
			"product_id": 12,
			"quantity": 5
		}
	]
}

###