version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: commerse
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: p@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
