# Generated by Django 4.2.3 on 2023-07-23 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0002_rename_order_productcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCart',
            new_name='OrderingProduct',
        ),
    ]
