# Generated by Django 4.2.3 on 2023-07-23 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0003_rename_productcart_orderingproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderingProduct',
            new_name='OrderingProducts',
        ),
    ]
