# Generated by Django 4.2.3 on 2023-07-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_rename_orderingproducts_orderingproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderingproduct',
            table='ordering_products',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
